studypy/django/projects/helloworld/basic_prj/urls.py
from django.conf.urls import include, url
#from django.conf.urls.defaults import *
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sample_app/', include('sample_app.urls', namespace='sample_app')),
    #url(r'^sample_app/', include("smaple_app.urls", namespace="sample_app")),
]

#urlpatterns = patterns( '',
#    url(r'^sample_app/', include('smaple_app.urls', namespace="sample_app")),
#    url(r'^admin/', admin.site.urls),
#)

studypy/django/projects/helloworld/sample_app/urls.py
from django.conf.urls import url
from sample_app import views 
#app_name = 'sample_app'
urlpatterns = [
    #url(r'^sample_app/', include('smaple_app.urls', namespace="sample_app")),
    #url(r'^P<videourl_id>\d+/$', views.)
    url(r'^index/$', views.index, name='index'),
    url(r'^write/$', views.write, name='write'),
    url(r'^write_ok/$', views.write_ok, name='write_ok'),
    url(r'^show_vlist/$', views.show_vlist, name='show_vlist'),
]

studypy/django/projects/helloworld/sample_app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class VideoCategory(models.Model):
    category = models.CharField(max_length=20)
    #pub_date = models.DateTimeField('date published') # 추후 다시 추가
    def __unicode__(self):
        return self.category

class VideoUrl(models.Model):
    #category = models.ForeignKey(VideoCategory)
    vod_id = models.AutoField(primary_key=True)
    subject = models.CharField(max_length=50)
    url = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    #pub_date = models.DateTimeField('date published') # 추후 다시 추가
    def __unicode__(self):
        return self.subject

studypy/django/projects/helloworld/sample_app/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from sample_app.models import VideoUrl, VideoCategory

# Create your views here.
def index(request):
    context = {'videourls' : 'helloworld'}
    return render(request, 'sample_app/index.html', context)

def write(request):
    return render(request, 'sample_app/write.html',{'test':'test'} )

def write_ok(request):
    print("category :: " + request.POST['category'])
    print("subject :: " + request.POST['subject'])
    print("url :: " + request.POST['url'])
    print("description :: " + request.POST['description'])
    m_subject = request.POST['subject']
    m_url = request.POST['url']
    m_description = request.POST['description']

    v = VideoUrl( subject=m_subject, url=m_url, description=m_description )
    #v.save(force_insert=True)
    v.save()
    #return render(request, 'sample_app/show_vlist.html',{'test':'test'})
    return HttpResponseRedirect(reverse('sample_app:show_vlist'),{'test':'test'})
    #return redirect('sample_app/show_vlist/')
    #return HttpResponseRedirect('sample_app:show_vlist')

#def list(request):
def show_vlist(request):
    print("view.py - list()")
    video_list = VideoUrl.objects.all()
    #vidoe_list = get_object_or_404(VideoUrl, pk=videourl_id)
    for vod in video_list:
        print('vod : ' + vod.subject)
    msg = { 'video_list' : video_list }
    #아래의 부분은 응? 어뜨케 고치지? ㅋㅋㅋ
    return render ( request, 'sample_app/show_vlist.html', msg )

studypy/django/projects/helloworld/sample_app/templates/sample_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
	Welcome, YOUTUBE urls scrapping        
    </title>
</head>
<body>
    <ul>
        <li><a href="/sample_app/write/">+Add URL</a></li>
        <li><a href="/sample_app/list/">Show list</a></li>
    </ul>
</body>
</html>

studypy/django/projects/helloworld/sample_app/templates/sample_app/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      VIDEO LIST
    </title>
</head>
<body>
  <form action="{% url 'sample_app:write_ok'%}" method="post">{% csrf_token %}
  <table>
    <tr>
      <td><p>title : </p></td>
      <td><input type="text" name="subject"/></td>
    </tr>
    <tr>
      <td><p>url : </p></td>
      <td><input type="text" name="url"/></td>
    </tr>
    <tr>
      <td><p>description : </p></td>
      <td><input type="text" name="description"/></td>
    </tr>
    <tr>
      <td><input type="hidden" name="category" value="Videos"/></td>
      <td colspan="2"><input type="submit" name="저장" /></td>
    </tr>
  </table>
  </form>
</body>
</html>

studypy/django/projects/helloworld/sample_app/templates/sample_app/show_vlist.html
<html>
 <head>
   <title>show list of videos</title>
 </head>
 <body>
   <h1> list of video urls  </h1>
{#   <ul>#}
{#     {% for vod in video_list %}#}
{#       <li><a href="{{ vod.url }}"> {{vod.subject}} </a> </li>#}
{#     {% endfor %}#}
{#   </ul>#}
   <table>
   {% for v in video_list %}
       <tr>
         <td><a href="{{ vod.url }}"> {{ vod.subjet }}</a> </td>
         <td>Edit</td>
       </tr>
   {% endfor %}
   </table>
 </body>
</html>

studypy/django/projects/helloworld/sample_app/templates/sample_app/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
	Welcome, YOUTUBE urls scrapping        
    </title>
</head>
<body>
  <form action="{% url 'sample_app:write_ok'%}" method="post">{% csrf_token %}
  <table>
    <tr>
      <td><p>title : </p></td>
      <td><input type="text" name="subject"/></td>
    </tr>
    <tr>
      <td><p>url : </p></td>
      <td><input type="text" name="url"/></td>
    </tr>
    <tr>
      <td><p>description : </p></td>
      <td><input type="text" name="description"/></td>
    </tr>
    <tr>
      <td><input type="hidden" name="category" value="Videos"/></td>
      <td colspan="2"><input type="submit" name="저장" /></td>
    </tr>
  </table>
  </form>
</body>
</html>

studypy/django/projects/helloworld/sample_app/templates/sample_app/write_ok.html
<html>
</html>